remote_theme: pages-themes/modernist@v0.2.0
plugins:
  - jekyll-remote-theme
relative_links:
  enabled: true
include:
  - README.md
  - index.md
title: ETL VISION PROJECT
description: The Purpose of this Project is to Demonstrate the design and execution of an ETL Pipeline using FHIR APIs for efficient Healthcare data integration
          
